"""Reset TTL state — remove online-evolution state and optionally preserve static TTL copies.

Default behavior (recommended):
  - Keep data/ttl working-copy files for static experiences/edges/adjacency
  - Remove dynamic checkpoint/results and TTL-added experiences/edges/adj entries

Leaves untouched:
  data/experiences/           ← static experience library (Phase 1+2, READ-ONLY)
  data/experience_graph_adj/  ← static adjacency (Phase 2)
  data/experience_edges/      ← static edges (Phase 2)
  data/networkx/              ← static graph HTML (not TTL version)

Usage:
  python scripts/reset_ttl.py                              # soft reset (preserve static TTL copy)
  python scripts/reset_ttl.py --yes                        # skip confirmation
  python scripts/reset_ttl.py --drop-ttl-dir --yes         # hard reset (delete whole data/ttl)
"""
import argparse
import json
import os
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

TTL_DIR = os.path.join("data", "ttl")
STATIC_EXP_CANDIDATES = [
    os.path.join("data", "role_edges", "role_edges.jsonl"),
    os.path.join("data", "experiences", "experiences.jsonl"),
    os.path.join("data", "preprocessed", "experiences.jsonl"),
]
STATIC_ADJ   = os.path.join("data", "experience_graph_adj", "experience_graph_adj.jsonl")
STATIC_EDGES = os.path.join("data", "experience_edges", "experience_edges.jsonl")
STATIC_LEXICON = os.path.join("data", "lexicon", "lexicon.json")
STATIC_ENTITY_POSTINGS = os.path.join("data", "entity_postings", "entity_postings.json")

# Files outside data/ttl/ that may be generated by TTL runs
EXTRA_FILES = [
    os.path.join("data", "networkx", "experience_graph_ttl_interactive.html"),
    os.path.join("data", "networkx", "experience_graph_ttl.html"),
    os.path.join("data", "networkx", "experience_graph_ttl.gpickle"),
    os.path.join("data", "networkx", "experience_graph_ttl.json"),
    os.path.join("data", "networkx", "entity_graph_ttl_interactive.html"),
    os.path.join("data", "networkx", "entity_graph_ttl.html"),
    os.path.join("data", "networkx", "entity_graph_ttl.gpickle"),
    os.path.join("data", "networkx", "entity_graph_ttl.json"),
]

# TTL初始化时需要复制的5个文件（与历史版本一致）
# entity_stats 直接从 data/ 读取，不需要副本
TTL_COPY_TARGETS = [
    ("__STATIC_EXP__",  os.path.join("experiences", "experiences.jsonl")),
    (STATIC_ADJ,        os.path.join("experience_graph_adj", "experience_graph_adj.jsonl")),
    (STATIC_EDGES,      os.path.join("experience_edges", "experience_edges.jsonl")),
    (STATIC_LEXICON,    os.path.join("lexicon", "lexicon.json")),
    (STATIC_ENTITY_POSTINGS, os.path.join("entity_postings", "entity_postings.json")),
]


def _resolve_static_exp_path() -> str:
    for p in STATIC_EXP_CANDIDATES:
        if os.path.exists(p):
            return p
    return STATIC_EXP_CANDIDATES[0]


def _refresh_ttl_static_copies(ttl_dir: str) -> None:
    """Copy static files into TTL working dir.

    TTL初始化时复制的文件（与历史版本一致）：
      - experiences/experiences.jsonl     (从 preprocessed/ 优先)
      - experience_graph_adj/...jsonl
      - experience_edges/...jsonl
      - lexicon/lexicon.json
      - entity_postings/entity_postings.json

    entity_stats 直接从 data/entity_stats/ 读取，不需要副本。
    """
    print(f"\n刷新TTL静态副本（{len(TTL_COPY_TARGETS)}个文件）...")
    os.makedirs(ttl_dir, exist_ok=True)
    copied = 0
    static_exp_path = _resolve_static_exp_path()
    for src, rel_dst in TTL_COPY_TARGETS:
        if src == "__STATIC_EXP__":
            src = static_exp_path
        dst = os.path.join(ttl_dir, rel_dst)
        if not os.path.exists(src):
            print(f"  [警告] 静态源文件缺失，跳过: {src}")
            continue
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)
        print(f"  已复制: {src} → {dst}")
        copied += 1
    print(f"  完成: 已复制 {copied}/{len(TTL_COPY_TARGETS)} 个文件。")


def main():
    parser = argparse.ArgumentParser(description="Reset TTL state to initial (pre-evolution)")
    parser.add_argument("--yes", "-y", action="store_true", help="Skip confirmation prompt")
    parser.add_argument(
        "--drop-ttl-dir",
        action="store_true",
        help="Hard reset: delete the whole TTL directory instead of preserving static working copies.",
    )
    parser.add_argument(
        "--ttl-dir", default=TTL_DIR, help=f"TTL directory to delete (default: {TTL_DIR})"
    )
    args = parser.parse_args()

    ttl_dir = args.ttl_dir

    # ------------------------------------------------------------------
    # Show what will be deleted
    # ------------------------------------------------------------------
    targets = []
    if os.path.exists(ttl_dir) and args.drop_ttl_dir:
        targets.append(ttl_dir)
    for p in EXTRA_FILES:
        if os.path.exists(p):
            targets.append(p)

    has_destructive_targets = bool(targets)
    if not has_destructive_targets:
        print("No existing TTL runtime artifacts to delete.")
        print("Will still (re)create TTL static working copies.")

    if args.drop_ttl_dir:
        print("The following will be permanently deleted:")
        for t in targets:
            if os.path.isdir(t):
                n = sum(1 for _ in Path(t).rglob("*") if _.is_file())
                size = sum(f.stat().st_size for f in Path(t).rglob("*") if f.is_file())
                print(f"  [DIR]  {t}  ({n} files, {size/1024:.1f} KB)")
            else:
                size = os.path.getsize(t)
                print(f"  [FILE] {t}  ({size/1024:.1f} KB)")
        print()
        print("Static data (data/experiences/, data/experience_graph_adj/, data/experience_edges/)")
        print("will NOT be touched.")
        print()
    else:
        print("Soft reset mode (preserve static TTL working copies):")
        print("  - Will clear dynamic checkpoint/results and TTL-added records")
        print("  - Will keep static records mirrored under data/ttl/")
        for p in EXTRA_FILES:
            if os.path.exists(p):
                print(f"  - Will delete: {p}")
        print()

    # ------------------------------------------------------------------
    # Confirm
    # ------------------------------------------------------------------
    if has_destructive_targets and not args.yes:
        answer = input("Proceed? [y/N] ").strip().lower()
        if answer not in ("y", "yes"):
            print("Aborted.")
            return

    # ------------------------------------------------------------------
    # Delete
    # ------------------------------------------------------------------
    if args.drop_ttl_dir:
        for t in targets:
            if os.path.isdir(t):
                shutil.rmtree(t)
                print(f"Deleted directory: {t}")
            else:
                os.remove(t)
                print(f"Deleted file:      {t}")
    else:
        # 1) Remove dynamic-only files
        dynamic_files = [
            os.path.join(ttl_dir, "graph_state.json"),
            os.path.join(ttl_dir, "results.jsonl"),
        ]
        for p in dynamic_files:
            if os.path.exists(p):
                os.remove(p)
                print(f"Deleted file:      {p}")

        # 2) Load static ID sets
        static_exp_ids = set()
        static_exp_path = _resolve_static_exp_path()
        if os.path.exists(static_exp_path):
            with open(static_exp_path, encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        row = json.loads(line)
                        eid = row.get("id", "")
                        if eid:
                            static_exp_ids.add(eid)

        static_adj_ids = set()
        static_edge_keys = set()
        if os.path.exists(STATIC_ADJ):
            with open(STATIC_ADJ, encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        row = json.loads(line)
                        eid = row.get("exp_id", "")
                        if eid:
                            static_adj_ids.add(eid)
        if os.path.exists(STATIC_EDGES):
            with open(STATIC_EDGES, encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        row = json.loads(line)
                        src = row.get("src", "")
                        dst = row.get("dst", "")
                        if src and dst:
                            static_edge_keys.add(":".join(sorted([src, dst])))

        # 3) Rewrite TTL working copies with static-only records
        ttl_exp = os.path.join(ttl_dir, "experiences", "experiences.jsonl")
        ttl_adj = os.path.join(ttl_dir, "experience_graph_adj", "experience_graph_adj.jsonl")
        ttl_edges = os.path.join(ttl_dir, "experience_edges", "experience_edges.jsonl")

        if os.path.exists(ttl_exp):
            kept = []
            with open(ttl_exp, encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        row = json.loads(line)
                        if row.get("id", "") in static_exp_ids:
                            kept.append(row)
            with open(ttl_exp, "w", encoding="utf-8") as f:
                for row in kept:
                    f.write(json.dumps(row, ensure_ascii=False) + "\n")
            print(f"Rewrote static-only: {ttl_exp} ({len(kept)} records)")

        if os.path.exists(ttl_adj):
            kept = []
            with open(ttl_adj, encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        row = json.loads(line)
                        eid = row.get("exp_id", "")
                        if eid in static_adj_ids:
                            neighbors = [
                                nb for nb in row.get("neighbors", [])
                                if nb.get("neighbor", "") in static_exp_ids
                            ]
                            kept.append({"exp_id": eid, "neighbors": neighbors})
            with open(ttl_adj, "w", encoding="utf-8") as f:
                for row in kept:
                    f.write(json.dumps(row, ensure_ascii=False) + "\n")
            print(f"Rewrote static-only: {ttl_adj} ({len(kept)} nodes)")

        if os.path.exists(ttl_edges):
            kept = []
            with open(ttl_edges, encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        row = json.loads(line)
                        src = row.get("src", "")
                        dst = row.get("dst", "")
                        k = ":".join(sorted([src, dst])) if src and dst else ""
                        if k and k in static_edge_keys:
                            kept.append(row)
            with open(ttl_edges, "w", encoding="utf-8") as f:
                for row in kept:
                    f.write(json.dumps(row, ensure_ascii=False) + "\n")
            print(f"Rewrote static-only: {ttl_edges} ({len(kept)} edges)")

        # 4) Remove TTL-only intermediate dirs if present
        purge_dirs = [
            os.path.join(ttl_dir, "core_entities"),
            os.path.join(ttl_dir, "role_edges"),
            os.path.join(ttl_dir, "similarity"),
            os.path.join(ttl_dir, "entity_postings"),
            os.path.join(ttl_dir, "lexicon"),   # 重置后由 _refresh 重新复制静态版本
        ]
        for d in purge_dirs:
            if os.path.isdir(d):
                shutil.rmtree(d)
                print(f"Deleted directory: {d}")

        for p in EXTRA_FILES:
            if os.path.exists(p):
                os.remove(p)
                print(f"Deleted file:      {p}")

    # Ensure TTL has fresh standalone static copies after reset.
    _refresh_ttl_static_copies(ttl_dir)

    print()
    print("Reset complete. TTL state has been restored to initial (pre-evolution) state.")
    print("Run `python main_ttl.py` to start a fresh evolution.")


if __name__ == "__main__":
    main()
